version: '3'

services:
  postgres:
    container_name: postgres_pcp_container
    image: postgres:11.13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pg-demo}
      PGDATA: /${POSTGRES_DB:-pg-demo}-data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    # volumes:
